/**
 * distiller/assemble.ts — deterministic skill-artifact assembly.
 *
 * Given a skill spec (slug/role/description/triggers) and an authored body,
 * produce the full set of artifacts needed to land a skill: the SKILL.md text
 * (deterministic frontmatter + ANONYMISED body), the manifest entry, the
 * RESOLVER row, and a routing-eval stub. Pure — the executor decides how to
 * apply them. The body is anonymised as a HARD GATE (throws on residual PII).
 */

import { anonymiseOrThrow } from './anonymise.ts';
import type { SkillRole } from './types.ts';

/** Default read-only tool inventory for a decision-support skill. */
export const DEFAULT_SKILL_TOOLS = ['search', 'query', 'get_page', 'list_pages'] as const;

export interface SkillSpec {
  slug: string;
  role: SkillRole;
  description: string;
  triggers: string[];
  tools?: string[];
}

export interface SkillArtifacts {
  slug: string;
  skillPath: string;
  skillContent: string;
  manifestEntry: { name: string; path: string; description: string };
  resolverRow: string;
  resolverSection: string;
  routingEvalPath: string;
  routingEval: string;
}

/** Build the deterministic YAML frontmatter block (inclusive of the fences). */
export function buildFrontmatter(spec: SkillSpec): string {
  const tools = spec.tools && spec.tools.length ? spec.tools : [...DEFAULT_SKILL_TOOLS];
  const lines = [
    '---',
    `name: ${spec.slug}`,
    'version: 0.1.0',
    'description: |',
    `  ${spec.description.replace(/\s+/g, ' ').trim()}`,
    'triggers:',
    ...spec.triggers.map((t) => `  - "${t.replace(/"/g, '')}"`),
    `role: ${spec.role}`,
    'tools:',
    ...tools.map((t) => `  - ${t}`),
    'mutating: false',
    '---',
  ];
  return lines.join('\n');
}

/** Build the RESOLVER table row for this skill (routed to Patient care). */
export function buildResolverRow(spec: SkillSpec): string {
  const trig = spec.triggers.map((t) => `"${t.replace(/"/g, '')}"`).join(', ');
  return `| ${trig} | \`skills/${spec.slug}/SKILL.md\` (role: ${spec.role}) |`;
}

/**
 * Build a routing-eval stub: one paraphrased intent per trigger. The intent
 * CONTAINS the trigger (so it structurally routes) but never EQUALS it (so it
 * passes the "intent must paraphrase, not copy" lint).
 */
export function buildRoutingEval(spec: SkillSpec): string {
  const header = [
    `// Routing eval fixtures for skills/${spec.slug} (generated by the distiller).`,
    '// Each line: {intent, expected_skill}. Intent paraphrases the trigger, never copies it.',
  ];
  const rows = spec.triggers
    .slice(0, 4)
    .map((t) => JSON.stringify({ intent: `Guidance on ${t} for a resident`, expected_skill: spec.slug }));
  return [...header, ...rows].join('\n') + '\n';
}

/**
 * Assemble all artifacts. `body` is the authored SKILL.md body (markdown, no
 * frontmatter); it is anonymised as a hard gate before embedding. Throws if the
 * body still carries an identifier after scrubbing, or if it is malformed.
 */
export function assembleSkill(spec: SkillSpec, body: string): SkillArtifacts {
  const cleanBody = anonymiseOrThrow(body).trim();
  if (!/^#\s/m.test(cleanBody)) {
    throw new Error('assembleSkill: body must contain an H1 heading (# ...).');
  }
  const description = anonymiseOrThrow(spec.description).trim();
  const cleanSpec: SkillSpec = { ...spec, description };

  const skillContent = `${buildFrontmatter(cleanSpec)}\n\n${cleanBody}\n`;
  return {
    slug: spec.slug,
    skillPath: `skills/${spec.slug}/SKILL.md`,
    skillContent,
    manifestEntry: { name: spec.slug, path: `${spec.slug}/SKILL.md`, description },
    resolverRow: buildResolverRow(cleanSpec),
    resolverSection: 'Patient care',
    routingEvalPath: `skills/${spec.slug}/routing-eval.jsonl`,
    routingEval: buildRoutingEval(cleanSpec),
  };
}
